version: '3'
services:
  csv-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: csv-server
    volumes:
      - ./csvapi:/usr/src/app/public
    ports:
      - '4000:4000'
    